### ISSUE TITLE
关于DetectionPadCollator

### ISSUE THREAD

**Issue by Asthestarsfalll** [MegEngine/Models#116]
![image](https://user-images.githubusercontent.com/72954905/142751952-9a583d80-be45-42dc-abb5-98e58f5a92fb.png)
这里似乎是会将不同尺寸的输入图片pad到相同尺寸然后concat起来？
这样做不会有什么影响吗？
或者是我理解错了吗？

**Comment by wjfwzzc** [comment]
在`ShortestEdgeResize`里会先把不同尺寸的图片resize到同一短边尺寸，`DetectionPadCollator`只是把长边pad到对齐。
