### ISSUE TITLE
Spiky GPU utilization when training classification task

### ISSUE THREAD

**Issue by aptsunny** [MegEngine/Models#2]
Hi,
When running train script for image classification directory - resnet/shufflenet etc. I notice very spiky GPU utilization behavior.

Scale lr with batch size and  ngpus:
> python3 train.py --data /home/ubuntu/imagenet --arch resnet50 --batch-size 64 --learning-rate 0.1 --ngpus 8

Open a separate terminal window and run:
watch -n0.1 nvidia-smi

You should see GPU-utilization almost oscillate between 60% - 100%
This is consistency reproducible with all trials.

If we expect spikes, my question would be why? If we don't, can you try to reproduce this GPU spike behavior and detail what part of the code causes it? Perhaps performance improvements could be gained if the utilization did not spike?

Is this expected behavior? I observe this behavior during a single training run, and it appears to happen during every epoch. Something’s not right and I don’t know how to debug/diagnose it under the framework, perhaps some specific diagnostic tools if you don't mind.

**Comment by zhouyizhuang-megvii** [comment]
Hi, thank you for your feedback. It is probably due to the insufficient data supply. By default we use 4 workers for each GPU, and the optimal number may vary depending on your machine. Try doubling it with `--workers 8`, and see if the problem remains.

**Comment by aptsunny** [comment]
> Hi, thank you for your feedback. It is probably due to the insufficient data supply. By default we use 4 workers for each GPU, and the optimal number may vary depending on your machine. Try doubling it with `--workers 8`, and see if the problem remains.
> 
> Also to note that the training script by default scaling up learning rate by the number of gpus you use. To reproduce the result, just use a learning rate of 0.025 for batch size 64 regardless of how many gpus you have.
> 
> https://github.com/MegEngine/Models/blob/d67b5efe43b909b565347b1b804aba603449046e/official/vision/classification/resnet/train.py#L68

THX！
I would like to ask if there is a **method or some specific diagnostic tools for controlling GPU-utilization**.
In addition, I also encountered a dataloader interruption during training, and the weird GPU monitoring behavior is as shown below.
![GpJJ8s.png](https://s1.ax1x.com/2020/03/26/GpJJ8s.png)

Error:
```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/chainer_p36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ubuntu/anaconda3/envs/chainer_p36/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/workspace/Models/official/vision/classification/resnet/train.py", line 196, in worker
    _, valid_acc, valid_acc5 = infer(valid_func, valid_queue, args, epoch=epoch)
  File "/home/ubuntu/workspace/Models/official/vision/classification/resnet/train.py", line 259, in infer
    for step, (image, label) in enumerate(data_queue):
  File "/home/ubuntu/anaconda3/envs/chainer_p36/lib/python3.6/site-packages/megengine/data/dataloader.py", line 152, in __next__
    minibatch = self._get_next_batch()
  File "/home/ubuntu/anaconda3/envs/chainer_p36/lib/python3.6/site-packages/megengine/data/dataloader.py", line 512, in _get_next_batch
    batch_data = self._try_get_next_batch()
  File "/home/ubuntu/anaconda3/envs/chainer_p36/lib/python3.6/site-packages/megengine/data/dataloader.py", line 501, in _try_get_next_batch
    self._check_workers()
  File "/home/ubuntu/anaconda3/envs/chainer_p36/lib/python3.6/site-packages/megengine/data/dataloader.py", line 441, in _check_workers
    raise RuntimeError("data collecting worker died. {}".format(exitcode))
RuntimeError: data collecting worker died. None
```

**Comment by zhouyizhuang-megvii** [comment]
Observing that the exitcode is `None`, so the worker was probably killed by system due to out-of-memory. The increase in memory occupation may be caused by the increase number of workers as I recommended. So... unfortunately, try to reduce the number of workers...[sad] Reducing the batch size may also help.

> I would like to ask if there is a method or some specific diagnostic tools for controlling GPU-utilization.

So far MegEngine doesn't provide native support for it.

**Comment by aptsunny** [comment]
Thanks for your help.
