### ISSUE TITLE
hub.load导入"retinanet_res50_1x_800size"报错

### ISSUE THREAD

**Issue by davidishere** [MegEngine/Models#35]
## 环境
1.系统环境：Ubuntu 18.04
2.MegEngine版本：0.4.0
3.python版本：3.6.8
4.模型名称：retinanet_res50_1x_800size

## 复现步骤
1.
2.
3.

## 请提供关键的代码片段便于追查问题

from megengine import hub
model = hub.load(
    "megengine/models",
    "retinanet_res50_1x_800size",
    pretrained=True,
)

## 请提供完整的日志及报错信息

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/usr/local/lib/python3.6/dist-packages/megengine/hub/hub.py", line 202, in load
    raise RuntimeError("Cannot find callable {} in hubconf.py".format(entry))
RuntimeError: Cannot find callable retinanet_res50_1x_800size in hubconf.py

**Comment by FateScript** [comment]
> ## 环境
> 1.系统环境：Ubuntu 18.04
> 2.MegEngine版本：0.4.0
> 3.python版本：3.6.8
> 4.模型名称：retinanet_res50_1x_800size
> 
> ## 复现步骤
> 
> ## 请提供关键的代码片段便于追查问题
> from megengine import hub
> model = hub.load(
> "megengine/models",
> "retinanet_res50_1x_800size",
> pretrained=True,
> )
> 
> ## 请提供完整的日志及报错信息
> Traceback (most recent call last):
> File "", line 4, in
> File "/usr/local/lib/python3.6/dist-packages/megengine/hub/hub.py", line 202, in load
> raise RuntimeError("Cannot find callable {} in hubconf.py".format(entry))
> RuntimeError: Cannot find callable retinanet_res50_1x_800size in hubconf.py

看起来是cache没更新的问题，可以使用
```Python
model = hub.load(
    "megengine/models", "retinanet_res50_1x_800size",
    pretrained=True, use_cache=False
)
```
试一下，应该会重新download一份新的retinanet

**Comment by davidishere** [comment]
谢谢！OK了！

**Comment by davidishere** [comment]
修改后报下面的错误：

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/megengine/hub/hub.py", line 206, in load
    module = getattr(hubmodule, entry)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/megengine/hub/hub.py", line 317, in pretrained_model_func
    model = func(**kwargs)
  File "/root/.cache/megengine/hub/e093aa62cdf8f313/official/vision/detection/retinanet_res50_coco_1x_800size.py", line 23, in retinanet_res50_coco_1x_800size
    return models.RetinaNet(models.RetinaNetConfig(), batch_size=batch_size, **kwargs)
  File "/root/.cache/megengine/hub/e093aa62cdf8f313/official/vision/detection/models/retinanet.py", line 39, in __init__
    bottom_up = resnet50(norm=layers.get_norm(self.cfg.resnet_norm))
  File "/root/.cache/megengine/hub/e093aa62cdf8f313/official/vision/detection/layers/basic/norm.py", line 71, in get_norm
    "SyncBN": M.SyncBatchNorm,
AttributeError: module 'megengine.module' has no attribute 'SyncBatchNorm'

**Comment by FateScript** [comment]
> 修改后报下面的错误：
> 
> Traceback (most recent call last):
> File "", line 1, in
> File "/usr/local/lib/python3.6/dist-packages/megengine/hub/hub.py", line 206, in load
> module = getattr(hubmodule, entry)(*args, **kwargs)
> File "/usr/local/lib/python3.6/dist-packages/megengine/hub/hub.py", line 317, in pretrained_model_func
> model = func(**kwargs)
> File "/root/.cache/megengine/hub/e093aa62cdf8f313/official/vision/detection/retinanet_res50_coco_1x_800size.py", line 23, in retinanet_res50_coco_1x_800size
> return models.RetinaNet(models.RetinaNetConfig(), batch_size=batch_size, **kwargs)
> File "/root/.cache/megengine/hub/e093aa62cdf8f313/official/vision/detection/models/retinanet.py", line 39, in **init**
> bottom_up = resnet50(norm=layers.get_norm(self.cfg.resnet_norm))
> File "/root/.cache/megengine/hub/e093aa62cdf8f313/official/vision/detection/layers/basic/norm.py", line 71, in get_norm
> "SyncBN": M.SyncBatchNorm,
> AttributeError: module 'megengine.module' has no attribute 'SyncBatchNorm'

哦哦，这个是0.5.0里面即将发布的Sync bn，目前0.4.0还不支持，可以把这一行注释掉

**Comment by davidishere** [comment]
您好，我看了retinanet的配置，并没有用Sync bn
class RetinaNetConfig:
    def __init__(self):
        self.resnet_norm = "FrozenBN"
        self.backbone_freeze_at = 2

**Comment by FateScript** [comment]
> 您好，我看了retinanet的配置，并没有用Sync bn
> class RetinaNetConfig:
> def **init**(self):
> self.resnet_norm = "FrozenBN"
> self.backbone_freeze_at = 2
> 
> retinanet_res50_coco_1x_800size.py
> 
> from megengine import hub
> 
> from official.vision.detection import models
> 
> @hub.pretrained(
> "https://data.megengine.org.cn/models/weights/"
> "retinanet_d3f58dce_res50_1x_800size_36dot0.pkl"
> )
> def retinanet_res50_coco_1x_800size(batch_size=1, **kwargs):
> r"""
> RetinaNet trained from COCO dataset.
> `"RetinaNet" <https://arxiv.org/abs/1708.02002>`_
> """
> return models.RetinaNet(models.RetinaNetConfig(), batch_size=batch_size, **kwargs)
> 
> Net = models.RetinaNet
> Cfg = models.RetinaNetConfig
> 
> 并没有调用retinanet_res50_coco_1x_800size_syncbn.py

没有使用sync bn的原因是相关的模型还在训练中，另外模型提交到hub也需要一定时间

**Comment by davidishere** [comment]
那是不是现在retinanet模型的预训练权重还无法使用？需要自己重新训练

**Comment by FateScript** [comment]
> 那是不是现在retinanet模型的预训练权重还无法使用？需要自己重新训练

可以使用啊，只不过是sync bn的功能不支持而已，正常RetinaNet使用的是Frozen BN

**Comment by davidishere** [comment]
您好，现在的代码中就是使用的Frozen BN，不知道为什么说用了sync bn，您可以试一下看看是不是有问题？

**Comment by FateScript** [comment]
> 您好，现在的代码中就是使用的Frozen BN，不知道为什么说用了sync bn，您可以试一下看看是不是有问题？

您好，[这个](https://github.com/MegEngine/Models/blob/514908dd346063a0b4ce1c3825ed145fe0509bef/official/vision/detection/layers/basic/norm.py#L71)地方多了一个SyncBn，而现在0.4.0版本的MegEngine并不支持，我的意思是注释掉这一行你就可以正常使用RetinaNet了，您可以试一下

**Comment by davidishere** [comment]
OK，谢谢！
