### ISSUE TITLE
python3 train.py ERROR

### ISSUE THREAD

**Issue by dlwslb** [MegEngine/Models#4]
Traceback (most recent call last):
  File "train.py", line 41, in <module>
    import megengine as mge
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/megengine/__init__.py", line 3, in <module>
    raise ValueError("This is an placeholder only")
ValueError: This is an placeholder only

**Comment by zhouyizhuang-megvii** [comment]
Seems that you didn't get the correct megengine installed. Please uninstall it and try the official source instead of pypi
```
pip3 install megengine -f https://megengine.org.cn/whl/mge.html
```

**Comment by dlwslb** [comment]
我是用咱们官网的安装命令安装 版本是0.0.1.dev啥的好像,卸载重新安装就能好使?

天&nbsp;&nbsp; 
 空
 的
 晨
 星


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yizhuang Zhou"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月27日(星期五) 上午8:35
收件人:&nbsp;"MegEngine/Models"<Models@noreply.github.com&gt;;
抄送:&nbsp;"开心果"<739562628@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MegEngine/Models] python3 train.py ERROR (#4)





 
Seems that you didn't get the correct megengine installed. Please uninstall it and try the official source instead of pypi
 pip3 install megengine -f https://megengine.org.cn/whl/mge.html

**Comment by zhouyizhuang-megvii** [comment]
哦重新看了一下你是mac，目前没有为mac编译的binary。

https://megengine.org.cn/whl/mge.html

**Comment by dlwslb** [comment]
知道了谢谢,辛苦!



天&nbsp;&nbsp; 
 空
 的
 晨
 星


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yizhuang Zhou"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月27日(星期五) 上午8:50
收件人:&nbsp;"MegEngine/Models"<Models@noreply.github.com&gt;;
抄送:&nbsp;"开心果"<739562628@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MegEngine/Models] python3 train.py ERROR (#4)





 
哦重新看了一下你是mac，目前没有为mac编译的binary。
 
https://megengine.org.cn/whl/mge.html
