### ISSUE TITLE
执行Models/official/vision/detection/inference.py 发生错误

### ISSUE THREAD

**Issue by paradise2011** [MegEngine/Models#5]
## 环境
1.系统环境：ubuntu 18
2.MegEngine版本：MegEngine-0.3.1
3.python版本：python3.6.9
4.模型名称：resnet50

## 复现步骤
1.从网络下载训练文件
from megengine import hub
model = hub.load('megengine/models', 'resnet50', pretrained=True)
2. 执行Models/official/vision/detection/inference.py 

ython3 tools/inference.py -f retinanet_res50_1x_800size.py -i ../../assets/cat.jpg -m /home/liyeguang/python_example/resnet50/resnet50_fbaug_76254_4e14b7d1.pkl
3. 发生错误

## 请提供完整的日志及报错信息
30 15:43:50 Load Model : /home/AAA/python_example/resnet50/resnet50_fbaug_76254_4e14b7d1.pkl completed
30 15:43:50[mgb] WRN cuda unavailable: no CUDA-capable device is detected(100) ndev=-1
Traceback (most recent call last):
  File "tools/inference.py", line 68, in <module>
    main()
  File "tools/inference.py", line 50, in main
    model.load_state_dict(mge.load(args.model)["state_dict"])
KeyError: 'state_dict'

**Comment by paradise2011** [comment]
参考文档:Models/official/vision/detection/ReadMe.md

**Comment by zhouyizhuang-megvii** [comment]
感谢反馈，请把50行的`["state_dict"]`去掉，改为`mge.load(args.model)`。这是由于我们更新了预训练权重但未更新代码导致的，我们将尽快修复。

**Comment by paradise2011** [comment]
非常感谢你的回复。
1修改了inference.py的50行代码为：model.load_state_dict(mge.load(args.model))。重新测试。
2 执行Models/official/vision/detection/inference.py出现下面错误：
Traceback (most recent call last):
  File "tools/inference.py", line 68, in <module>
    main()
  File "tools/inference.py", line 50, in main
    model.load_state_dict(mge.load(args.model))
  File "/home/liyeguang/.local/lib/python3.6/site-packages/megengine/module/module.py", line 342, in load_state_dict
    "Unused params violate `strict=True`, unused={}".format(unused)。

3 继续修改inference.py的50行代码为：model.load_state_dict(mge.load(args.model),strict=False)，进行测试。
4 执行Models/official/vision/detection/inference.py，能够正常结束，生成results.jpg文件。
  但是出现了很多下面的警告：
30 18:33:26 WRN skip loading param `backbone.bottom_up.bn1.bias`
30 18:33:26 WRN skip loading param `backbone.bottom_up.bn1.running_mean`
30 18:33:26 WRN skip loading param `backbone.bottom_up.bn1.running_var`
30 18:33:26 WRN skip loading param `backbone.bottom_up.bn1.weight`
30 18:33:26 WRN skip loading param `backbone.bottom_up.conv1.weight`
30 18:33:26 WRN skip loading param `backbone.bottom_up.fc.bias`


5.仔细查看了result.jpg,和cat.jpg相比，没有看到任何变化。 
   我个人理解：result.jpg中是否圈出猫的轮廓？----还请多多指教。

**Comment by zhouyizhuang-megvii** [comment]
这是由于模型与你预训练权重不匹配导致的。你通过`model = hub.load('megengine/models', 'resnet50', pretrained=True)`下载的是ResNet50的分类模型，因此在加载入Detection模型时没有正确加载，因此网络不会输出期望的结果。

请通过`model = hub.load('megengine/models', 'retinanet_res50_1x_800size', pretrained=True)`或者直接从
https://data.megengine.org.cn/models/weights/retinanet_d3f58dce_res50_1x_800size_36dot0.pkl 下载Detection用的预训练权重。

**Comment by paradise2011** [comment]
按照你的建议，重新获取了训练权重文件。重新测试之后，results.jpg文件能够标记出猫的轮廓了。
非常感谢！
