### ISSUE TITLE
imagenet数据集

### ISSUE THREAD

**Issue by aspnetcs** [MegEngine/Models#62]
在https://github.com/MegEngine/Models/tree/master/official/quantization中，命令python3 train.py -a resnet18 -d /path/to/imagenet --mode normal 中的imagenet数据集在哪里下载？http://www.image-net.org/，这里吗？flower(https://www.kaggle.com/c/flower-classification-with-tpus/data)数据集可以用在这个命令中，正确运行吗？
![捕获](https://user-images.githubusercontent.com/14257859/92132404-b1b1fd80-ee39-11ea-8228-49785ceee920.PNG)
用megstudio创建项目，选取数据集，怎么没有kaggle flower 数据集？讲课中，是有的，在哪里有？

**Comment by FateScript** [comment]
1. ImageNet 官方数据集在[这里](http://www.image-net.org/)
2. 如果需要自己的数据集实现，需要自己写对应的dataloader，谢谢
