### ISSUE TITLE
训练出错（https://github.com/MegEngine/Models/tree/master/official/quantization）

### ISSUE THREAD

**Issue by aspnetcs** [MegEngine/Models#63]
执行 python3 train.py -a resnet18 -d /home/rootx/Models/official/quantization/dataset/flowers-recognition/ --mode normal
出错了，缺少文件，咋办？
![2020-09-05_094759](https://user-images.githubusercontent.com/14257859/92294235-f2566780-ef5c-11ea-8a19-ddee0e2205d8.jpg)

root@rootx-virtual-machine:/home/rootx/Models/official/quantization# python3 train.py -a resnet18 -d /home/rootx/Models/official/quantization/dataset/flowers-recognition/ --mode normal
err: Failed to load CUDA Driver API library
err: failed to load cuda func: cuCtxGetCurrent
err: failed to load cuda func: cuCtxGetCurrent
05 09:43:15[mgb] ERR cudaGetDeviceCount failed: CUDA driver version is insufficient for CUDA runtime version (err 35)
05 09:43:15[mgb] WRN cuda unavailable: CUDA driver version is insufficient for CUDA runtime version(35) ndev=-1
05 09:43:16 preparing dataset..
05 09:43:16 WRN devkit directory /home/rootx/Models/official/quantization/dataset/flowers-recognition/ILSVRC2012_devkit_t12 does not exists
05 09:43:16 checksum devkit tar file /home/rootx/Models/official/quantization/dataset/flowers-recognition/ILSVRC2012_devkit_t12.tar.gz ...
Traceback (most recent call last):
  File "train.py", line 309, in <module>
    main()
  File "train.py", line 65, in main
    worker(0, 1, args)
  File "train.py", line 152, in worker
    train_dataset = data.dataset.ImageNet(args.data, train=True)
  File "/usr/local/lib/python3.6/dist-packages/megengine/data/dataset/vision/imagenet.py", line 97, in __init__
    self._prepare_devkit()
  File "/usr/local/lib/python3.6/dist-packages/megengine/data/dataset/vision/imagenet.py", line 245, in _prepare_devkit
    calculate_md5(raw_file) == checksum
  File "/usr/local/lib/python3.6/dist-packages/megengine/data/dataset/vision/utils.py", line 56, in calculate_md5
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/rootx/Models/official/quantization/dataset/flowers-recognition/ILSVRC2012_devkit_t12.tar.gz'
root@rootx-virtual-machine:/home/rootx/Models/official/quantization# 

## 环境
1.系统环境：
2.MegEngine版本：
3.python版本：
4.模型名称：

## 复现步骤
1.
2.
3.

**Comment by aspnetcs** [comment]
用这些吗？

http://www.image-net.org/challenges/LSVRC/2012/nnoupb/ILSVRC2012_img_test.tar
http://www.image-net.org/challenges/LSVRC/2012/nnoupb/ILSVRC2012_img_val.tar
http://www.image-net.org/challenges/LSVRC/2012/nnoupb/ILSVRC2012_img_train.tar
http://www.image-net.org/challenges/LSVRC/2012/nnoupb/ILSVRC2012_devkit_t12.tar
http://www.image-net.org/challenges/LSVRC/2012/nnoupb/ILSVRC2012_bbox_train_v2.tar

**Comment by ChaiMind** [comment]
GIYF, STFW.

**Comment by aspnetcs** [comment]
http://www.image-net.org/challenges/LSVRC/2012/nnoupb/ILSVRC2012_devkit_t12.tar  下载不下来，咋办？

**Comment by aspnetcs** [comment]
[ImageNet.zip](https://github.com/MegEngine/Models/files/5177494/ImageNet.zip)
用这个能下载

**Comment by aspnetcs** [comment]
imagenet，过于庞大，可用于训练测试的有小型数据集吗？

**Comment by FateScript** [comment]
> imagenet，过于庞大，可用于训练测试的有小型数据集吗？

首先，models里面的模型是用于复现，用小数据集如mnist的确可以，但是没有人会在mnist上做试验，如果你想要玩一些toy模型，自己写一个dataloader就可以
