### ISSUE TITLE
需要贵公司thundernet的开源

### ISSUE THREAD

**Issue by tianlanshidai** [MegEngine/Models#84]

**Comment by MegChai** [comment]
Models 存储库主要存放一些较为主流的深度模型实现，对于 Thundernet 的模型代码是否开源需要尊重原作者的主观意愿，而且早期的内部源码和现在的 MegEngine 不是相同的版本，可以尝试发邮件给作者询问实现细节。

**Comment by tianlanshidai** [comment]
收到，感谢



---原始邮件---
发件人: "Chai"<notifications@github.com&gt;
发送时间: 2020年12月1日(周二) 晚上8:27
收件人: "MegEngine/Models"<Models@noreply.github.com&gt;;
抄送: "tianlanshidai"<www.ecbt.com@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [MegEngine/Models] 需要贵公司thundernet的开源 (#84)




 
Models 存储库主要存放一些较为主流的深度模型实现，对于 Thundernet 的模型代码是否开源需要尊重原作者的主观意愿，而且早期的内部源码和现在的 MegEngine 不是相同的版本，可以尝试发邮件给作者询问实现细节。
